from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional

TypeEq = Callable[[Any, Any], bool]
NodeFn = Callable[[NodeArgs], None]
PostFn = Callable[[Graph], None]


class RPort:
    def __init__(self, refs: Dict[int, Any], gate: Any, rport: Any) -> None: ...
    def value(self) -> Any: ...
    def has_value(self) -> bool: ...
    def as_input(self) -> RPort: ...


class MPort:
    def __init__(self, refs: Dict[int, Any], gate: Any, libc: Any, mport: Any, eq: TypeEq) -> None: ...
    def value(self) -> Any: ...
    def has_value(self) -> bool: ...
    def set_value(self, new_value: Any) -> None: ...
    def unset_value(self) -> None: ...
    def as_input(self) -> RPort: ...


class EPort:
    def __init__(self, refs: Dict[int, Any], gate: Any, libc: Any, eport: Any, eq: TypeEq) -> None: ...
    def to_direct(self) -> MPort: ...
    def as_input(self) -> RPort: ...


class Node:
    def __init__(self, refs: Dict[int, Any], gate: Any, node: Any) -> None: ...
    def outputs(self) -> List[RPort]: ...


class Graph:
    def __init__(self, refs: Dict[int, Any], fns: Any, gate: Any, libc: Any, graph: Any) -> None: ...
    def port(self, eq: TypeEq, value: Optional[Any] = None) -> EPort: ...
    def node(self, fn: NodeFn, inputs: List[Any], outputs: List[TypeEq]) -> Node: ...


class Core:
    def __init__(self, refs: Dict[int, Any], fns: Any, gate: Any, libc: Any, core: Any) -> None: ...
    def destroy(self) -> None: ...
    def post(self, fn: PostFn) -> None: ...
    def apply(self, fn: PostFn) -> None: ...
    def commit(self) -> None: ...


class Gate:
    def __init__(self, gate: Any) -> None: ...
    def create_core(self) -> Core: ...


class NodeArgs:
    core: Core
    inputs: List[Any]
    outputs: List[MPort]
    def __init__(self, core: Core, inputs: List[Any], outputs: List[MPort]) -> None: ...


def create_core() -> Core: ...


__all__: List[str]
